### ISSUE TITLE
[wip] Remove raw curl attributes and replace it with 'ssl.certificate_authority'

### ISSUE THREAD

**Issue by zachbadgett** [orkestra/OrkestraTransactorBundle#4]
Currently:

``` yml
  orkestra.transactor.guzzle_client:
    class: Guzzle\Http\Client
    arguments:
      - ''
      - { 'curl.options': { 'CURLOPT_CAINFO': %orkestra.ca_bundle.path%, 'CURLOPT_SSL_VERIFYPEER': true } }
```

This requires you to specify a path to the ca, if you don't, an error occurs. We can make this better by using guzzle's ssl.certificate_authority configuration and making 'orkestra.ca_bundle.path' default to true or false.

``` yml
  orkestra.transactor.guzzle_client:
    class: Guzzle\Http\Client
    arguments:
      - ''
      - { 'ssl.certificate_authority': %orkestra.ca_bundle.path% }
```

in Configuration.php:

``` php
$this->container->setParameter('orkestra.ca_bundle.path', ($capath != null) ? $capath : false);
```

This will allow guzzle to use the default cacert that it comes with, use a specified ca path, use 'system' for the system cacert or false to disable ssl.
